/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#bb9c8c",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "secondary": "#725a37",
        "tertiary-fixed": "#f8deca",
        "tertiary-fixed-dim": "#dbc2af",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#463629",
        "surface": "#fdf9f3",
        "on-error": "#ffffff",
        "primary-container": "#4a3428",
        "primary-fixed": "#ffdbca",
        "primary": "#321f14",
        "surface-tint": "#73594b",
        "on-secondary-container": "#775f3b",
        "on-tertiary-container": "#b69e8d",
        "surface-dim": "#ddd9d4",
        "on-secondary-fixed-variant": "#594322",
        "on-primary-fixed": "#29170d",
        "on-tertiary-fixed": "#26190d",
        "on-secondary-fixed": "#291800",
        "outline": "#81746f",
        "inverse-surface": "#31302d",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "surface-container": "#f1ede7",
        "on-surface": "#1c1c18",
        "on-primary-fixed-variant": "#594235",
        "primary-fixed-dim": "#e1c0af",
        "background": "#fdf9f3",
        "secondary-container": "#fcdbae",
        "secondary-fixed-dim": "#e1c297",
        "surface-variant": "#e6e2dc",
        "surface-container-high": "#ebe8e2",
        "on-tertiary-fixed-variant": "#554335",
        "tertiary": "#2f2115",
        "surface-bright": "#fdf9f3",
        "error": "#ba1a1a",
        "surface-container-highest": "#e6e2dc",
        "outline-variant": "#d3c3bc",
        "on-background": "#1c1c18",
        "secondary-fixed": "#ffddb1",
        "inverse-primary": "#e1c0af",
        "on-surface-variant": "#4f453f",
        "inverse-on-surface": "#f4f0ea",
        "surface-container-low": "#f7f3ed"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "display": ["Playfair Display", "serif"],
        "display-mobile": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "body-sm": ["Manrope", "sans-serif"],
        "label-lg": ["Manrope", "sans-serif"],
        "label-md": ["Manrope", "sans-serif"],
        "label-sm": ["Manrope", "sans-serif"],
        serif: ["Playfair Display", "serif"],
        sans: ["Manrope", "sans-serif"],
      },
      fontSize: {
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "display-mobile": ["38px", { lineHeight: "46px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.12em", fontWeight: "600" }],
        "headline-sm": ["22px", { lineHeight: "30px", fontWeight: "500" }],
        "headline-lg": ["40px", { lineHeight: "50px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "30px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "0", fontWeight: "400" }],
        "display": ["56px", { lineHeight: "68px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.08em", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
